# Generated by Django 5.0 on 2024-01-05 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateField(verbose_name='Дата оплаты')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сумма оплаты')),
                ('pay_type', models.CharField(choices=[('trans', 'Перевод'), ('cash', 'Наличные')], default='trans', max_length=10, verbose_name='способ оплаты')),
                ('paid_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.course', verbose_name='Оплаченный курс')),
                ('paid_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.lesson', verbose_name='Оплаченный урок')),
            ],
        ),
    ]
