# Generated by Django 5.0 on 2024-01-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='price_identity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Price_ID in Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status_paid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус оплаты'),
        ),
    ]
