# Generated by Django 5.0 on 2024-01-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_price_identity_payment_status_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Сумма оплаты'),
        ),
    ]
