# Generated by Django 5.0 on 2024-01-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='price_identity',
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_session',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Session_ID in Stripe'),
        ),
    ]
