# Generated by Django 5.0 on 2024-01-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_payment_price_identity_payment_stripe_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для оплаты'),
        ),
    ]
