# Generated by Django 5.0 on 2024-01-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма оплаты'),
        ),
    ]
