# Generated by Django 5.0 on 2024-01-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_payment_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status_paid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_session',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Session_ID in Stripe'),
        ),
    ]
