# Generated by Django 5.0 on 2024-01-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_payment_stripe_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка для оплаты'),
        ),
    ]
