# Generated by Django 5.0 on 2024-01-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_session',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Session_ID in Stripe'),
        ),
    ]
