# Generated by Django 5.0 on 2024-01-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_course_price_lesson_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=1000000, verbose_name=' Стоимость курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='price',
            field=models.PositiveIntegerField(default=500000, verbose_name=' Стоимость урока'),
        ),
    ]
