# Generated by Django 4.2.9 on 2024-01-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0006_alter_course_price_alter_lesson_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
